### ISSUE TITLE
Add R.utils to containers

### ISSUE THREAD

**Issue by lpiep** [kaufman-lab/build_containers#57]
While `data.table` is installed in the geospatial-plus container, it doesn't appear to have the `R.utils` dependency installed by default, which is needed to use `fread` on compressed files. 

```
 Error in fread("data/my_compressed_file.csv.gz") : 
  To read gz and bz2 files directly, fread() requires 'R.utils' package which cannot be found. Please install 'R.utils' using 'install.packages('R.utils')'.
```

**Comment by myoung3** [comment]
Hi Logan,
This should be as easy as adding R.utils to the install.packages calls in
this file:
https://github.com/kaufman-lab/build_containers/blob/main/build_scripts/geospatial_plus__4.1.0/%25post
Can you try adding a pull request? It would be good to see if this works
for someone else.

Michael

**Comment by lpiep** [comment]
Sure thing. Should this change go into all containers?

**Comment by lpiep** [comment]
Never mind, I see that the geospatial containers all inherit from geospatial_plus.

**Comment by myoung3** [comment]
Yep, since the other two geospatial containers inherit from
geospatial_plus, it's only necessary to make this change in the file I
specified.

Note for this to work you'll need to pull the repo to the server, then set
up the git pre-commit hooks (see the readme). Trying to change this on
github.com won't work since the git pre-commit hooks won't occur (and build
will fail)

You don't need to change the other containers:
mkl_centos7 is not used for anything and doesn't have packages installed;
rather, it just serves as an example of how to install MKL and R (building
R from source using MKL) on centos 7 (the same linux version as the brain
cluster)
and nationalspatiotemporal container is for the national spatiotemporal
process to run in and shouldn't be altered unless something breaks there.

**Comment by lpiep** [comment]
@myoung3 I think I may need additional permissions for the container registry. 
```
FATAL:   Unable to push image to oci registry: unable to push: unexpected status: 403 Forbidden
Error: Process completed with exit code 255.
```

**Comment by myoung3** [comment]
@lpiep yeah see the comment I made on the PR..I've hopefully fixed it so try making a whiteapace only change to that post file to restart the build

**Comment by lpiep** [comment]
@myoung3 you were correct that the issue was a result of submitting the PR from a fork rather than branch. The new PR has passed all tests, so I'll go ahead and merge it later today unless you'd like to review.
